### ISSUE TITLE
No possible use .thumbdata files if they are stored in Windows 10

### ISSUE THREAD

**Issue by NessunoIM** [qq316107934/android-thumbdata-extract#1]
Is possible to extract thums from .thumbdata file if it is stored on PC?

**Comment by ms300** [comment]
yes,you can:
1.copy .thumbdata file to tmp folder
2.assign the .thumbdata filename for the variable "item"
3.just run the code after line 30

**Comment by NessunoIM** [comment]
Thank you!

**Comment by ghost** [comment]
Hi, Can somobody post an example of how to make it work?
I never user Python before.
getting this error: IndentationError: unexpected indent
